画图支持dall-e-3模型
cssxsh/mirai-openai-plugin pull request #47
Opened 2023-11-16 10:02 UTC by fufuzhou

2023-11-17 09:30 UTC, cssxsh requested changes

2023-11-17 09:30 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/openai/image/ImageRequest.kt
>              require(number in 1..10) { "Must be between 1 and 10" }
根据 `model` 检查 `style` 
https://platform.openai.com/docs/api-reference/images/create#images-create-style

2023-11-17 09:31 UTC, cssxsh commented on src/main/kotlin/xyz/cssxsh/openai/image/ImageRequest.kt
>              require(number in 1..10) { "Must be between 1 and 10" }
另外记得格式化一下代码

2023-11-20 06:12 UTC, fufuzhou commented
没怎么用过github，那边改了一下，加了个检查，然后怎么操作？

2023-11-20 07:06 UTC, merged